name: contribute-on-discussion

on:
  discussion:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment && github.event.discussion.category.name == '기고채널'
    steps:
      - run: |
          curl --location --request POST ${{ secrets.SLACK_WEBHOOK_URL }} --header 'Content-Type: application/json' --data-raw '{
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "새로운 기고 💡",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*<${{ github.event.discussion.html_url }}|#${{ github.event.discussion.number }} ${{ github.event.discussion.title }}>*"
                },
                "accessory": {
                  "type": "button",
                  "style": "primary",
                  "text": {
                    "type": "plain_text",
                    "text": "GitHub에서 확인하기",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "${{ github.event.discussion.html_url }}",
                  "action_id": "button-action"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "기고자"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.discussion.user.html_url }}|${{ github.event.discussion.user.login }}>"
                  },
                  {
                    "type": "image",
                    "image_url": "${{ github.event.discussion.user.avatar_url }}",
                    "alt_text": "Contributor"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.event.discussion.created_at }} 등록"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }'
